config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, except: [:index, :show, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= raw t(".message",
      url_home: link_to(t(".url_home"), "http://www.railstutorial.org/"),
      url_author: link_to(t(".url_author"), "http://www.michaelhartl.com/")) %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), about_path %></li>
      <li><%= link_to t("static_pages.contact.title"), contact_path %></li>
      <li><%= link_to t(".url_new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title"), root_path %></li>
        <li><%= link_to t("static_pages.help.title"), help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              data: {toggle: "dropdown"} do %>
              <%= current_user.name %><%= content_tag :b, "", class: "caret" %>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>